# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c5390f026fc387dbea767030a23b439b3a8e936ac89773081f28e683d4da814540847b83743a5988128b2916f137c0bde392384e0ac7ea7bf9ea96b38d83e145

test:
  secret_key_base: 2a5cc679fb640d4276030e253afc4914208b47af063b778b55b746c58a51cc7f30c8059f2cd83f29b757ad3716134bc63cf83134b7f4b6226e8d102fa7425357

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
